language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

after_success:
  - mvn deploy --settings $HOME/.m2/settings.xml